name: Releases
on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Zip locales
      run: zip -r Localization.zip . -i "Localization/*"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.zip
          tools/*.cmd

